import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { getToken, getUserDetails } from "../../../utils/auth";
import { toastMsg } from "../../../utils/utils";
import { createEchoInstance } from "../../../utils/echo";
import {
  bdBackupApi,
  dbListApi,
  executeQueryApi,
  exportExcelQueryApi,
  tableListApi,
} from "../../../api/endpoints";

import DatabaseSidebar from "../queryComponents/DatabaseSidebar";
import SqlWorkspace from "../queryComponents/SqlWorkspace";
import ExportConfigModal from "../queryComponents/ExportConfigModal";

export default function QueryEditorUI() {
  const [selectedDb, setSelectedDb] = useState("");
  const [query, setQuery] = useState("");
  const textareaRef = useRef(null);

  const [dbList, setDbList] = useState([]);
  const [tablesList, setTableList] = useState([]);
  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  const [isButtonDisabled, setIsButtonDisabled] = useState(false);
  const [isDbLoading, setIsDbLoading] = useState(false);
  const [isTableLoading, setIsTableLoading] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [hint, setHint] = useState(false);

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  // Modal & Configuration States
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [exportTitle, setExportTitle] = useState("Details Report");
  const [exportFileName, setExportFileName] = useState("Report");
  const [modalSql, setModalSql] = useState("");
  const [isConfigExecuting, setIsConfigExecuting] = useState(false);

  const [cardsConfig, setCardsConfig] = useState([]);
  const [childGroups, setChildGroups] = useState([]);
  const [isExporting, setIsExporting] = useState(false);

  const profile = getUserDetails();
  const token = getToken();
  const navigator = useNavigate();

  // Helper to trigger direct browser file download
  const triggerDownload = (url, fileName) => {
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", fileName);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  // -------------------------------------------------------------
  // WebSocket Lifecycle: Connects on Mount & Disconnects on Unmount
  // -------------------------------------------------------------
  useEffect(() => {
    // Re-evaluate user info directly inside effect
    const currentUser = getUserDetails();
    const userId = currentUser?.id || profile?.id;

    if (!userId) {
      console.warn("[WebSocket] Setup skipped: User profile ID missing.", currentUser);
      return;
    }

    console.log("[WebSocket] Mounting: Creating Echo instance...");
    const echoInstance = createEchoInstance();

    const channelName = `user.${userId}`;
    console.log(`[WebSocket] Subscribing to channel: ${channelName}`);

    const channel = echoInstance.private(channelName);

    channel.subscribed(() => {
      console.log(`[WebSocket] Successfully subscribed to: ${channelName}`);
    });

    // Event Listener: Excel Export
    channel.listen(".ExcelExportReady", (eventData) => {
      console.log("[WebSocket] Event received: .ExcelExportReady", eventData);
      setIsExporting(false);

      if (eventData.status) {
        const currentToken = getToken();
        if (currentToken && currentToken !== eventData?.token) return;

        triggerDownload(eventData.download_url, eventData.file_name);
        toastMsg("Excel export completed successfully!", "success");
        setIsExportModalOpen(false);
      } else {
        toastMsg(eventData.message || "Failed to process export.", "error");
      }
    });

    // Event Listener: DB Backup
    channel.listen(".DbBackupReady", (eventData) => {
      console.log("[WebSocket] Event received: .DbBackupReady", eventData);
      setIsExporting(false);

      if (eventData.status) {
        const currentToken = getToken();
        if (currentToken && currentToken !== eventData?.token) return;

        triggerDownload(eventData.download_url, eventData.file_name);
        toastMsg("Database backup downloaded successfully!", "success");
        setIsExportModalOpen(false);
      } else {
        toastMsg(eventData.message || "Failed to process backup.", "error");
      }
    });

    // Cleanup on Component Unmount
    return () => {
      console.log("[WebSocket] Unmounting: Disconnecting Echo connection...");
      channel.stopListening(".ExcelExportReady");
      channel.stopListening(".DbBackupReady");
      echoInstance.leave(channelName);
      echoInstance.disconnect();
    };
  }, [profile?.id]);

  // Auto detect card configuration logic
  const autoDetectColumnsFromQueryAndData = (sqlStatement, responseData) => {
    if (!responseData?.headers || responseData.headers.length === 0) return;

    const firstRow = responseData.data?.[0] || {};
    const detectedChildGroups = [];
    const jsonChildMap = {};

    responseData.headers.forEach((headerKey) => {
      let rawVal = firstRow[headerKey];
      if (typeof rawVal === "string") {
        try {
          rawVal = JSON.parse(rawVal);
        } catch (e) {}
      }

      if (
        Array.isArray(rawVal) &&
        rawVal.length > 0 &&
        typeof rawVal[0] === "object"
      ) {
        detectedChildGroups.push(headerKey);
        jsonChildMap[headerKey] = Object.keys(rawVal[0]);
      }
    });

    const jsonAggRegex = /jsonb?_agg\s*\([^)]+\)\s+(?:AS\s+)?([a-zA-Z0-9_]+)/gi;
    let match;
    while ((match = jsonAggRegex.exec(sqlStatement)) !== null) {
      const aliasName = match[1];
      if (!detectedChildGroups.includes(aliasName)) {
        detectedChildGroups.push(aliasName);
      }
    }

    setChildGroups(detectedChildGroups);

    const initialCards = [];
    const parentCols = [{ key: "serial_no", label: "#", type: "parent" }];

    responseData.headers.forEach((key) => {
      if (!detectedChildGroups.includes(key)) {
        parentCols.push({
          key: key,
          label: key
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          type: "parent",
        });
      }
    });

    initialCards.push({
      cardId: "parent_" + Date.now(),
      title: "PARENT INFORMATION",
      type: "parent",
      metaHeader: "PROPERTY INFORMATION",
      subMetaHeader: "General Details",
      columns: parentCols,
    });

    detectedChildGroups.forEach((childKey) => {
      const childCols = [];
      const keysList = jsonChildMap[childKey] || [];

      keysList.forEach((subKey) => {
        childCols.push({
          key: subKey,
          label: subKey
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          type: `child_${childKey}`,
        });
      });

      const formattedName = childKey.replace(/_/g, " ").toUpperCase();
      initialCards.push({
        cardId: `${childKey}_${Date.now()}`,
        title: `${formattedName} (CHILD)`,
        type: `child_${childKey}`,
        metaHeader: `${formattedName} DETAILS`,
        subMetaHeader: "Child Records",
        columns: childCols,
      });
    });

    setCardsConfig(initialCards);
  };

  useEffect(() => {
    if (data && cardsConfig.length === 0) {
      autoDetectColumnsFromQueryAndData(query, data);
    }
  }, [data]);

  const handleOpenExportModal = () => {
    let activeQuery = query;
    if (textareaRef.current) {
      const { selectionStart, selectionEnd } = textareaRef.current;
      if (selectionStart !== selectionEnd) {
        activeQuery = query.substring(selectionStart, selectionEnd);
      }
    }
    setModalSql(activeQuery);
    setIsExportModalOpen(true);
  };

  const handleStartConfig = async () => {
    if (!modalSql.trim()) {
      toastMsg("Please enter a SQL statement", "error");
      return;
    }

    let cleanedSql = modalSql
      .replace(/\s+LIMIT\s+\d+(\s+OFFSET\s+\d+)?/gi, "")
      .trim();
    cleanedSql = cleanedSql.replace(/;+$/, "");
    const configSql = `${cleanedSql} LIMIT 1`;

    setIsConfigExecuting(true);
    try {
      const response = await axios.post(
        executeQueryApi,
        { conn: selectedDb, statement: configSql },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response?.data?.status && response?.data?.data) {
        autoDetectColumnsFromQueryAndData(configSql, response.data.data);
        toastMsg(
          "Configuration loaded successfully with single record!",
          "success"
        );
      } else {
        toastMsg(response?.data?.message || "Failed to execute query", "error");
      }
    } catch (err) {
      toastMsg("Execution error while parsing configuration", "error");
    } finally {
      setIsConfigExecuting(false);
    }
  };

  const handleResetConfig = () => {
    setCardsConfig([]);
    setChildGroups([]);
    toastMsg("Configuration reset successfully!", "info");
  };

  useEffect(() => {
    const fetchDb = async () => {
      if (!profile?.roleDtls?.some((item) => item?.id == 1)) {
        toastMsg("Permission Denied!!!", "blank");
        setTimeout(() => navigator(-1), 5000);
        return;
      }
      setIsDbLoading(true);
      try {
        const response = await axios.post(
          dbListApi,
          {},
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) setDbList(response?.data?.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsDbLoading(false);
      }
    };
    fetchDb();
  }, [token]);

  useEffect(() => {
    const fetchTable = async () => {
      setIsTableLoading(true);
      setTableList([]);
      try {
        const response = await axios.post(
          tableListApi,
          { conn: selectedDb },
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) setTableList(response?.data?.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsTableLoading(false);
      }
    };
    if (token) fetchTable();
  }, [token, selectedDb]);

  const executeSql = async () => {
    setIsButtonDisabled(true);
    let statement = query;
    if (textareaRef.current) {
      const { selectionStart, selectionEnd } = textareaRef.current;
      if (selectionStart !== selectionEnd) {
        statement = query.substring(selectionStart, selectionEnd);
      }
    }
    try {
      const response = await axios.post(
        executeQueryApi,
        { conn: selectedDb, statement },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      if (response?.data?.status) {
        setData(response?.data?.data);
        setError("");
      } else {
        setData(null);
        setError(response?.data?.message);
      }
    } catch (err) {
      setData(null);
      setError("Something went wrong");
    } finally {
      setIsButtonDisabled(false);
    }
  };

  const handleTableClick = (tableName) => {
    const trimmed = query.trim();
    if (!trimmed || isAutoGenerated) {
      setQuery(`SELECT * FROM ${tableName} LIMIT 1`);
      setIsAutoGenerated(true);
      return;
    }
    setHint(true);
    setTimeout(() => setHint(false), 800);
  };

  const handleDownloadBackup = async () => {
    setIsDownloading(true);
    try {
      const response = await axios.post(
        bdBackupApi,
        { conn: selectedDb },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status) {
        toastMsg(response.data.message, "success");
      } else {
        toastMsg("Backup compilation issue encountered.", "error");
      }
    } catch (err) {
      toastMsg("Failed to process database backup file payload.", "error");
    } finally {
      setIsDownloading(false);
    }
  };

  const getFlatColumnsConfig = () => {
    const flatCols = [];
    cardsConfig.forEach((card) => {
      card.columns.forEach((col) => {
        flatCols.push({
          key: col.key,
          label: col.label,
          type: col.type || card.type,
          metaHeader: card.metaHeader,
          subMetaHeader: card.subMetaHeader,
        });
      });
    });
    return flatCols;
  };

  const handleExportExcel = async () => {
    let exportQuery = modalSql || query;
    setIsExporting(true);
    try {
      const response = await axios.post(
        exportExcelQueryApi,
        {
          conn: selectedDb,
          statement: exportQuery,
          title: exportTitle,
          file_name: exportFileName,
          columns: getFlatColumnsConfig(),
        },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status) {
        toastMsg("Excel generation started in background...", "success");
      } else {
        setIsExporting(false);
        toastMsg(response.data.message || "Export failed to trigger", "error");
      }
    } catch (err) {
      setIsExporting(false);
      toastMsg("Server error while initializing export process", "error");
    }
  };

  return (
    <div
      className={`${
        isDbLoading ? "pointer-events-none filter blur-sm" : ""
      } p-1 bg-gray-100 min-h-screen`}
    >
      <div className="bg-white shadow rounded p-1">
        {/* Top Header Actions */}
        <div className="mb-2 flex items-center justify-between px-2">
          <button
            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            className="bg-gray-200 hover:bg-gray-300 text-gray-700 px-3 py-1 text-xs font-medium rounded flex items-center gap-1 transition-colors"
          >
            {isSidebarOpen ? "← Hide Sidebar" : "→ Show Sidebar"}
          </button>
          <div className="flex gap-2">
            <button
              onClick={handleOpenExportModal}
              className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 text-sm rounded font-medium"
            >
              Configure Cards & Export Excel
            </button>
            <button
              onClick={handleDownloadBackup}
              disabled={isDownloading}
              className={`px-4 py-2 text-white rounded ${
                isDownloading
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-green-600 hover:bg-green-700"
              }`}
            >
              {isDownloading
                ? "Generating Backup..."
                : `Download Backup for (${selectedDb})`}
            </button>
          </div>
        </div>

        {/* Main Grid Workspace */}
        <div className="grid grid-cols-12 gap-4">
          <DatabaseSidebar
            isSidebarOpen={isSidebarOpen}
            selectedDb={selectedDb}
            setSelectedDb={setSelectedDb}
            dbList={dbList}
            tablesList={tablesList}
            isTableLoading={isTableLoading}
            handleTableClick={handleTableClick}
          />

          <SqlWorkspace
            isSidebarOpen={isSidebarOpen}
            textareaRef={textareaRef}
            query={query}
            setQuery={setQuery}
            hint={hint}
            setIsAutoGenerated={setIsAutoGenerated}
            executeSql={executeSql}
            isButtonDisabled={isButtonDisabled}
            error={error}
            data={data}
          />
        </div>
      </div>

      {/* Export Configuration Modal */}
      {isExportModalOpen && (
        <ExportConfigModal
          setIsExportModalOpen={setIsExportModalOpen}
          modalSql={modalSql}
          setModalSql={setModalSql}
          handleStartConfig={handleStartConfig}
          handleResetConfig={handleResetConfig}
          isConfigExecuting={isConfigExecuting}
          exportTitle={exportTitle}
          setExportTitle={setExportTitle}
          exportFileName={exportFileName}
          setExportFileName={setExportFileName}
          cardsConfig={cardsConfig}
          setCardsConfig={setCardsConfig}
          childGroups={childGroups}
          handleExportExcel={handleExportExcel}
          isExporting={isExporting}
        />
      )}
    </div>
  );
}