import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { getToken, getUserDetails } from "../../../utils/auth";
import { toastMsg } from "../../../utils/utils";
import {
  bdBackupApi,
  dbListApi,
  executeQueryApi,
  exportExcelQueryApi,
  QueryBroadcastAuthApi,
  tableListApi,
} from "../../../api/endpoints";

import DatabaseSidebar from "../queryComponents/DatabaseSidebar";
import SqlWorkspace from "../queryComponents/SqlWorkspace";
import ExportConfigModal from "../queryComponents/ExportConfigModal";

import Echo from "laravel-echo";
import Pusher from "pusher-js";

window.Pusher = Pusher;

// Fixed Laravel Echo configuration with dynamic Bearer Token authorization
export const echo = new Echo({
  broadcaster: "reverb",
  key: import.meta.env.VITE_REVERB_APP_KEY ,
  wsHost: import.meta.env.VITE_REVERB_HOST,
  wsPort: Number(import.meta.env.VITE_REVERB_PORT),
  wssPort: Number(import.meta.env.VITE_REVERB_PORT),
  forceTLS: (import.meta.env.VITE_REVERB_SCHEME ?? 'https') === 'https',
  enabledTransports: ["ws", "wss"],
  authorizer: (channel, options) => {
    return {
      authorize: (socketId, callback) => {
        const token = getToken() || localStorage.getItem("token");

        fetch(QueryBroadcastAuthApi, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
            Accept: "application/json",
          },
          body: JSON.stringify({
            socket_id: socketId,
            channel_name: channel.name,
          }),
        })
          .then((response) => {
            if (!response.ok) {
              throw new Error(`Auth failed with status ${response.status}`);
            }
            return response.json();
          })
          .then((data) => {
            callback(false, data);
          })
          .catch((error) => {
            callback(true, error);
          });
      },
    };
  },
});

export default function QueryEditorUI() {
  const [selectedDb, setSelectedDb] = useState("");
  const [query, setQuery] = useState("");
  const textareaRef = useRef(null);

  const [dbList, setDbList] = useState([]);
  const [tablesList, setTableList] = useState([]);
  const [data, setData] = useState(null);
  const [error, setError] = useState("");

  const [isButtonDisabled, setIsButtonDisabled] = useState(false);
  const [isDbLoading, setIsDbLoading] = useState(false);
  const [isTableLoading, setIsTableLoading] = useState(false);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [hint, setHint] = useState(false);

  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  // Modal & Configuration States
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [exportTitle, setExportTitle] = useState("Details Report");
  const [exportFileName, setExportFileName] = useState("Report");
  const [modalSql, setModalSql] = useState("");
  const [isConfigExecuting, setIsConfigExecuting] = useState(false);

  const [cardsConfig, setCardsConfig] = useState([]);
  const [childGroups, setChildGroups] = useState([]);
  const [isExporting, setIsExporting] = useState(false);

  const profile = getUserDetails();
  const token = getToken();
  const navigator = useNavigate();

  // Helper to trigger direct browser file download from standard Base64 string
  const triggerFileDownload = (fileBlob, fileName, mimeType) => {
    try {
      const byteCharacters = atob(fileBlob);
      const byteNumbers = new Array(byteCharacters.length);
      for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      const byteArray = new Uint8Array(byteNumbers);
      const blob = new Blob([byteArray], {
        type: mimeType || "application/vnd.ms-excel",
      });
      const downloadUrl = window.URL.createObjectURL(blob);

      const link = document.createElement("a");
      link.href = downloadUrl;
      link.setAttribute("download", fileName);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(downloadUrl);
    } catch (err) {
      console.error("Error blob converting:", err);
      toastMsg("Failed to construct downloaded file payload.", "error");
    }
  };

  // WebSocket Listener: Listen strictly on the private user broadcast channel
  useEffect(() => {
    if (!profile?.id) {
      console.warn("WebSocket setup skipped: User profile ID is missing.");
      return;
    }

    const channelName = `user.${profile.id}`;
    console.log(`[WebSocket] Subscribing to private channel: ${channelName}`);

    const channel = echo.private(channelName);

    // Debug: Log successful connection/subscription to channel
    channel.subscribed(() => {
      console.log(`[WebSocket] Successfully subscribed to channel: ${channelName}`);
    });

    // Listen for the custom event sent from Laravel
    channel.listen(".ExcelExportReady", (eventData) => {
      console.log("[WebSocket] Event received: .ExcelExportReady");
      console.log("[WebSocket] Full Payload Data:", eventData);

      setIsExporting(false);

      if (eventData.status) {
        console.log("token",token)
        if(token!=eventData?.token){
          return;
        }
        console.log("[WebSocket] Export status is true. Downloading Excel file...");

        const link = document.createElement("a");
        link.href = eventData.download_url;
        link.setAttribute("download", eventData.file_name);
        document.body.appendChild(link);
        link.click();
        link.remove();
        toastMsg("Excel export completed successfully!", "success");
        setIsExportModalOpen(false);
      } else {
        console.error("[WebSocket] Export payload returned an error status:", eventData.message);
        toastMsg(eventData.message || "Failed to process export.", "error");
      }
    });

    return () => {
      console.log(`[WebSocket] Unsubscribing from channel: ${channelName}`);
      echo.leave(`user.${profile.id}`);
    };
  }, [profile?.id]);

  // Auto detect card configuration logic
  const autoDetectColumnsFromQueryAndData = (sqlStatement, responseData) => {
    if (!responseData?.headers || responseData.headers.length === 0) return;

    const firstRow = responseData.data?.[0] || {};
    const detectedChildGroups = [];
    const jsonChildMap = {};

    responseData.headers.forEach((headerKey) => {
      let rawVal = firstRow[headerKey];
      if (typeof rawVal === "string") {
        try {
          rawVal = JSON.parse(rawVal);
        } catch (e) {}
      }

      if (
        Array.isArray(rawVal) &&
        rawVal.length > 0 &&
        typeof rawVal[0] === "object"
      ) {
        detectedChildGroups.push(headerKey);
        jsonChildMap[headerKey] = Object.keys(rawVal[0]);
      }
    });

    const jsonAggRegex = /jsonb?_agg\s*\([^)]+\)\s+(?:AS\s+)?([a-zA-Z0-9_]+)/gi;
    let match;
    while ((match = jsonAggRegex.exec(sqlStatement)) !== null) {
      const aliasName = match[1];
      if (!detectedChildGroups.includes(aliasName)) {
        detectedChildGroups.push(aliasName);
      }
    }

    setChildGroups(detectedChildGroups);

    const initialCards = [];
    const parentCols = [{ key: "serial_no", label: "#", type: "parent" }];

    responseData.headers.forEach((key) => {
      if (!detectedChildGroups.includes(key)) {
        parentCols.push({
          key: key,
          label: key
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          type: "parent",
        });
      }
    });

    initialCards.push({
      cardId: "parent_" + Date.now(),
      title: "PARENT INFORMATION",
      type: "parent",
      metaHeader: "PROPERTY INFORMATION",
      subMetaHeader: "General Details",
      columns: parentCols,
    });

    detectedChildGroups.forEach((childKey) => {
      const childCols = [];
      const keysList = jsonChildMap[childKey] || [];

      keysList.forEach((subKey) => {
        childCols.push({
          key: subKey,
          label: subKey
            .replace(/_/g, " ")
            .replace(/\b\w/g, (c) => c.toUpperCase()),
          type: `child_${childKey}`,
        });
      });

      const formattedName = childKey.replace(/_/g, " ").toUpperCase();
      initialCards.push({
        cardId: `${childKey}_${Date.now()}`,
        title: `${formattedName} (CHILD)`,
        type: `child_${childKey}`,
        metaHeader: `${formattedName} DETAILS`,
        subMetaHeader: "Child Records",
        columns: childCols,
      });
    });

    setCardsConfig(initialCards);
  };

  useEffect(() => {
    if (data && cardsConfig.length === 0) {
      autoDetectColumnsFromQueryAndData(query, data);
    }
  }, [data]);

  const handleOpenExportModal = () => {
    let activeQuery = query;
    if (textareaRef.current) {
      const { selectionStart, selectionEnd } = textareaRef.current;
      if (selectionStart !== selectionEnd) {
        activeQuery = query.substring(selectionStart, selectionEnd);
      }
    }
    setModalSql(activeQuery);
    setIsExportModalOpen(true);
  };

  const handleStartConfig = async () => {
    if (!modalSql.trim()) {
      toastMsg("Please enter a SQL statement", "error");
      return;
    }

    let cleanedSql = modalSql
      .replace(/\s+LIMIT\s+\d+(\s+OFFSET\s+\d+)?/gi, "")
      .trim();
    cleanedSql = cleanedSql.replace(/;+$/, "");
    const configSql = `${cleanedSql} LIMIT 1`;

    setIsConfigExecuting(true);
    try {
      const response = await axios.post(
        executeQueryApi,
        { conn: selectedDb, statement: configSql },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response?.data?.status && response?.data?.data) {
        autoDetectColumnsFromQueryAndData(configSql, response.data.data);
        toastMsg(
          "Configuration loaded successfully with single record!",
          "success"
        );
      } else {
        toastMsg(response?.data?.message || "Failed to execute query", "error");
      }
    } catch (err) {
      toastMsg("Execution error while parsing configuration", "error");
    } finally {
      setIsConfigExecuting(false);
    }
  };

  const handleResetConfig = () => {
    setCardsConfig([]);
    setChildGroups([]);
    toastMsg("Configuration reset successfully!", "info");
  };

  useEffect(() => {
    const fetchDb = async () => {
      if (!profile?.roleDtls?.some((item) => item?.id == 1)) {
        toastMsg("Permission Denied!!!", "blank");
        setTimeout(() => navigator(-1), 5000);
        return;
      }
      setIsDbLoading(true);
      try {
        const response = await axios.post(
          dbListApi,
          {},
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) setDbList(response?.data?.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsDbLoading(false);
      }
    };
    fetchDb();
  }, [token]);

  useEffect(() => {
    const fetchTable = async () => {
      setIsTableLoading(true);
      setTableList([]);
      try {
        const response = await axios.post(
          tableListApi,
          { conn: selectedDb },
          { headers: { Authorization: `Bearer ${token}` } }
        );
        if (response?.data?.status) setTableList(response?.data?.data);
      } catch (err) {
        console.error(err);
      } finally {
        setIsTableLoading(false);
      }
    };
    if (token) fetchTable();
  }, [token, selectedDb]);

  const executeSql = async () => {
    setIsButtonDisabled(true);
    let statement = query;
    if (textareaRef.current) {
      const { selectionStart, selectionEnd } = textareaRef.current;
      if (selectionStart !== selectionEnd) {
        statement = query.substring(selectionStart, selectionEnd);
      }
    }
    try {
      const response = await axios.post(
        executeQueryApi,
        { conn: selectedDb, statement },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      if (response?.data?.status) {
        setData(response?.data?.data);
        setError("");
      } else {
        setData(null);
        setError(response?.data?.message);
      }
    } catch (err) {
      setData(null);
      setError("Something went wrong");
    } finally {
      setIsButtonDisabled(false);
    }
  };

  const handleTableClick = (tableName) => {
    const trimmed = query.trim();
    if (!trimmed || isAutoGenerated) {
      setQuery(`SELECT * FROM ${tableName} LIMIT 1`);
      setIsAutoGenerated(true);
      return;
    }
    setHint(true);
    setTimeout(() => setHint(false), 800);
  };

  const handleDownloadBackup = async () => {
    setIsDownloading(true);
    try {
      const response = await axios.post(
        bdBackupApi,
        { conn: selectedDb },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status) {
        const { file_name, file_blob } = response.data.data;
        triggerFileDownload(file_blob, file_name, "application/zip");
        toastMsg(response.data.message, "success");
      } else {
        toastMsg("Backup compilation issue encountered.", "error");
      }
    } catch (err) {
      toastMsg("Failed to process database backup file payload.", "error");
    } finally {
      setIsDownloading(false);
    }
  };

  const getFlatColumnsConfig = () => {
    const flatCols = [];
    cardsConfig.forEach((card) => {
      card.columns.forEach((col) => {
        flatCols.push({
          key: col.key,
          label: col.label,
          type: col.type || card.type,
          metaHeader: card.metaHeader,
          subMetaHeader: card.subMetaHeader,
        });
      });
    });
    return flatCols;
  };

  // Triggers backend queued job & waits for WebSocket event
  const handleExportExcel = async () => {
    let exportQuery = modalSql || query;
    setIsExporting(true);
    try {
      const response = await axios.post(
        exportExcelQueryApi,
        {
          conn: selectedDb,
          statement: exportQuery,
          title: exportTitle,
          file_name: exportFileName,
          columns: getFlatColumnsConfig(),
        },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      if (response.data.status) {
        toastMsg("Excel generation started in background...", "success");
      } else {
        setIsExporting(false);
        toastMsg(response.data.message || "Export failed to trigger", "error");
      }
    } catch (err) {
      setIsExporting(false);
      toastMsg("Server error while initializing export process", "error");
    }
  };

  return (
    <div
      className={`${
        isDbLoading ? "pointer-events-none filter blur-sm" : ""
      } p-1 bg-gray-100 min-h-screen`}
    >
      <div className="bg-white shadow rounded p-1">
        {/* Top Header Actions */}
        <div className="mb-2 flex items-center justify-between px-2">
          <button
            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            className="bg-gray-200 hover:bg-gray-300 text-gray-700 px-3 py-1 text-xs font-medium rounded flex items-center gap-1 transition-colors"
          >
            {isSidebarOpen ? "← Hide Sidebar" : "→ Show Sidebar"}
          </button>
          <div className="flex gap-2">
            <button
              onClick={handleOpenExportModal}
              className="bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 text-sm rounded font-medium"
            >
              Configure Cards & Export Excel
            </button>
            <button
              onClick={handleDownloadBackup}
              disabled={isDownloading}
              className={`px-4 py-2 text-white rounded ${
                isDownloading
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-green-600 hover:bg-green-700"
              }`}
            >
              {isDownloading
                ? "Generating Backup..."
                : `Download Backup for (${selectedDb})`}
            </button>
          </div>
        </div>

        {/* Main Grid Workspace */}
        <div className="grid grid-cols-12 gap-4">
          <DatabaseSidebar
            isSidebarOpen={isSidebarOpen}
            selectedDb={selectedDb}
            setSelectedDb={setSelectedDb}
            dbList={dbList}
            tablesList={tablesList}
            isTableLoading={isTableLoading}
            handleTableClick={handleTableClick}
          />

          <SqlWorkspace
            isSidebarOpen={isSidebarOpen}
            textareaRef={textareaRef}
            query={query}
            setQuery={setQuery}
            hint={hint}
            setIsAutoGenerated={setIsAutoGenerated}
            executeSql={executeSql}
            isButtonDisabled={isButtonDisabled}
            error={error}
            data={data}
          />
        </div>
      </div>

      {/* Export Configuration Modal */}
      {isExportModalOpen && (
        <ExportConfigModal
          setIsExportModalOpen={setIsExportModalOpen}
          modalSql={modalSql}
          setModalSql={setModalSql}
          handleStartConfig={handleStartConfig}
          handleResetConfig={handleResetConfig}
          isConfigExecuting={isConfigExecuting}
          exportTitle={exportTitle}
          setExportTitle={setExportTitle}
          exportFileName={exportFileName}
          setExportFileName={setExportFileName}
          cardsConfig={cardsConfig}
          setCardsConfig={setCardsConfig}
          childGroups={childGroups}
          handleExportExcel={handleExportExcel}
          isExporting={isExporting}
        />
      )}
    </div>
  );
}