import React from "react";
import DataTableFullData from "../../../components/common/DataTableFullData";

export default function SqlWorkspace({
  isSidebarOpen,
  textareaRef,
  query,
  setQuery,
  hint,
  setIsAutoGenerated,
  executeSql,
  isButtonDisabled,
  error,
  data,
}) {
  return (
    <div className={`${isSidebarOpen ? "col-span-9" : "col-span-12"} transition-all duration-300`}>
      <textarea
        ref={textareaRef}
        rows={5}
        className={`w-full border rounded p-3 font-mono text-xs transition-all duration-300 ${
          hint ? "border-yellow-500 text-gray-500 bg-yellow-50 shadow-md" : "border-gray-300"
        }`}
        placeholder="Write your SQL query here..."
        value={query}
        onChange={(e) => {
          setQuery(e.target.value);
          setIsAutoGenerated(false);
        }}
      />

      <div className="mt-3 flex gap-3">
        <button
          disabled={isButtonDisabled}
          onClick={executeSql}
          className={`${
            isButtonDisabled ? "bg-gray-600 hover:bg-gray-300" : "bg-blue-600 hover:bg-blue-700"
          } text-white px-4 py-2 rounded`}
        >
          Execute
        </button>
      </div>

      <div className={`${isButtonDisabled ? "pointer-events-none filter blur-sm" : ""} mt-5 bg-gray-50 border p-3 rounded`}>
        {error && <p className="text-red-600 font-medium">{error}</p>}

        {data?.headers && data?.data ? (
          <DataTableFullData
            title={"Data Output"}
            startingItemsPerPage={10}
            isExport={true}
            headers={[{ label: "#", key: "serial" }, ...data.headers.map((h) => ({ label: h, key: h }))]}
            data={data.data}
            renderRow={(item, idx) => (
              <tr key={idx}>
                <td className="px-3 py-2 border">{idx + 1}</td>
                {data.headers.map((header, key) => (
                  <td key={key} className="px-3 py-2 border">
                    {String(item?.[header])}
                  </td>
                ))}
              </tr>
            )}
          />
        ) : data ? (
          <p className="text-green-500">{data}</p>
        ) : (
          !error && <p className="text-gray-500">No Data Found</p>
        )}
      </div>
    </div>
  );
}